### PR TITLE
Contact form

### PR DESCRIPTION
**Pull request by Irrreny**
Here is the Contact Form section:
image

### CODE REVIEW

**Review by sdmnc — APPROVED** [review]
Wow drop-downs with the days of the week!

**Review by IvanCeban — APPROVED** [review]
I'm impressed! Great job!

**Comment by IvanCeban** [comment]
Try to align the arrows in select according to the design. The rest is great

**Comment by Irrreny** [comment]
> Wow drop-downs with the days of the week!

hahah yeah, i wanted to make input date, but it wouldn't be the same as per design :)

**Pull request merged**
